# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosite', '0007_album_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
