# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosite', '0008_auto_20180613_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
